CREATE TABLE CONTA(
  ID NUMBER(4) CONSTRAINT PK_CONTA PRIMARY KEY,
  INFO_NOME VARCHAR2(50) CONSTRAINT NN_NOME NOT NULL,
  INFO_IDADE NUMBER(2) DEFAULT 18,
  SENHA VARCHAR2(16) CONSTRAINT NN_SENHA NOT NULL
);

CREATE TABLE EMAILS(
  ID NUMBER(4),
  EMAIL VARCHAR2(50) CONSTRAINT UN_EMAIL UNIQUE,
  CONSTRAINT PK_EMAILS PRIMARY KEY (ID,EMAIL),
  CONSTRAINT FK_EMAILS_CONTA_ID FOREIGN KEY (ID)
    REFERENCES CONTA(ID) ON DELETE CASCADE
);

CREATE TABLE JOGADOR(
  ID NUMBER(4),
  NICKNAME VARCHAR2(50),
  RANK NUMBER(3) DEFAULT 0 CONSTRAINT NN_RANK NOT NULL,
  CONSTRAINT PK_JOGADOR PRIMARY KEY (NICKNAME,ID),
  CONSTRAINT FK_JOGADOR_CONTA_ID FOREIGN KEY (ID)
    REFERENCES CONTA(ID) ON DELETE CASCADE
);

CREATE TABLE AMIZADE(
  LISTA_ID NUMBER(4),
  LISTA_NICK VARCHAR2(50),
  AMIGO_ID NUMBER(4),
  AMIGO_NICK VARCHAR2(50),
  CONSTRAINT PK_AMIZADE PRIMARY KEY (LISTA_ID,LISTA_NICK,AMIGO_ID,AMIGO_NICK),
  CONSTRAINT FK_AMIZADE_LISTA FOREIGN KEY (LISTA_ID,LISTA_NICK)
    REFERENCES JOGADOR(ID,NICKNAME) ON DELETE CASCADE,
  CONSTRAINT FK_AMIZADE_AMIGO FOREIGN KEY (AMIGO_ID,AMIGO_NICK)
    REFERENCES JOGADOR(ID,NICKNAME) ON DELETE CASCADE
);

CREATE TABLE PERSONAGEM(
  NOME VARCHAR2(50) CONSTRAINT PK_PERSONAGEM PRIMARY KEY,
  HP NUMBER(4) DEFAULT 0 CONSTRAINT NN_HP NOT NULL,
  ATAQUE NUMBER(4) DEFAULT 0 CONSTRAINT NN_ATAQUE NOT NULL,
  PODER NUMBER(4) DEFAULT 0 CONSTRAINT NN_PODER NOT NULL,
  ARMADURA NUMBER(4) DEFAULT 0 CONSTRAINT NN_ARMADURA NOT NULL,
  V_ATAQUE NUMBER(4) DEFAULT 0 CONSTRAINT NN_V_ATAQUE NOT NULL,
  V_MOVIMENTO NUMBER(4) DEFAULT 0 CONSTRAINT NN_V_MOVIMENTO NOT NULL
);

CREATE TABLE OFENSIVO(
  NOME VARCHAR2(50) PRIMARY KEY,
  CRITICO NUMBER(4) DEFAULT 0 CONSTRAINT NN_CRITIC NOT NULL,
  CONSTRAINT FK_OFENSIVO_PERSONAGEM_NOME FOREIGN KEY (NOME)
    REFERENCES PERSONAGEM (NOME) ON DELETE CASCADE
);

CREATE TABLE DEFENSIVO(
  NOME VARCHAR2(50) PRIMARY KEY,
  RESISTENCIA NUMBER(4) DEFAULT 0 CONSTRAINT NN_RESISTENCIA NOT NULL,
  CONSTRAINT FK_DEFENSIVO_PERSONAGEM_NOME FOREIGN KEY (NOME)
    REFERENCES PERSONAGEM (NOME) ON DELETE CASCADE
);

CREATE TABLE SUPORTE(
  NOME VARCHAR2(50) PRIMARY KEY,
  CURA NUMBER(4) DEFAULT 0 CONSTRAINT NN_CURA NOT NULL,
  CONSTRAINT FK_SUPORTE_PERSONAGEM_NOME FOREIGN KEY (NOME)
    REFERENCES PERSONAGEM (NOME) ON DELETE CASCADE
);

CREATE TABLE PARCERIA(
  OF_NOME VARCHAR2(50),
  DEF_NOME VARCHAR2(50),
  MITIGACAO NUMBER(4) DEFAULT 0 CONSTRAINT NN_MITIGACAO NOT NULL,
  CONSTRAINT PK_PARCERIA PRIMARY KEY (OF_NOME,DEF_NOME),
  CONSTRAINT FK_PARCERIA_OFENSIVO_NOME FOREIGN KEY (OF_NOME)
    REFERENCES OFENSIVO (NOME) ON DELETE CASCADE,
  CONSTRAINT FK_PARCERIA_DEFENSIVO_NOME FOREIGN KEY (DEF_NOME)
    REFERENCES DEFENSIVO (NOME) ON DELETE CASCADE
);

CREATE TABLE PROTEGE(
  DEF_NOME VARCHAR2(50),
  SUP_NOME VARCHAR2(50),
  EXALTACAO NUMBER(4) DEFAULT 0 CONSTRAINT  NN_PROTEGE NOT NULL,
  CONSTRAINT PK_PROTEGE PRIMARY KEY (DEF_NOME,SUP_NOME),
  CONSTRAINT FK_PROTEGE_DEFENSIVO_NOME FOREIGN KEY (DEF_NOME)
    REFERENCES DEFENSIVO (NOME) ON DELETE CASCADE,
  CONSTRAINT FK_PROTEGE_SUPORTE_NOME FOREIGN KEY (SUP_NOME)
    REFERENCES SUPORTE (NOME) ON DELETE CASCADE
);

CREATE TABLE POSSUI(
  ID NUMBER(4),
  NICK VARCHAR2(50),
  NOME VARCHAR2(50),
  CONSTRAINT PK_POSSUI PRIMARY KEY (ID,NICK,NOME),
  CONSTRAINT FK_POSSUI_JOGADOR_ID_NICK FOREIGN KEY (ID,NICK)
    REFERENCES JOGADOR (ID,NICKNAME) ON DELETE CASCADE,
  CONSTRAINT FK_POSSUI_PERSONAGEM_NOME FOREIGN KEY (NOME)
    REFERENCES PERSONAGEM (NOME) ON DELETE CASCADE
);

CREATE TABLE ITEM(
  NOME VARCHAR2(50) PRIMARY KEY,
  ATR_ATAQUE NUMBER(4) DEFAULT 0 CONSTRAINT NN_ATR_ATAQUE NOT NULL,
  ATR_VELOCIDADE NUMBER(4) DEFAULT 0 CONSTRAINT NN_ATR_VELOCIDADE NOT NULL,
  ATR_ARMADURA NUMBER(4) DEFAULT 0 CONSTRAINT NN_ATR_ARMADURA NOT NULL,
  ATR_PODER NUMBER(4) DEFAULT 0 CONSTRAINT NN_ATR_PODER NOT NULL
);

CREATE TABLE OBTEVE(
  ID NUMBER(4),
  NICK VARCHAR2(50),
  NOME VARCHAR2(50),
  CONSTRAINT PK_OBTEVE PRIMARY KEY (ID,NICK,NOME),
  CONSTRAINT FK_OBTEVE_JOGADOR_ID_NICK FOREIGN KEY (ID,NICK)
    REFERENCES JOGADOR (ID,NICKNAME) ON DELETE CASCADE,
  CONSTRAINT FK_OBTEVE_ITEM_NOME FOREIGN KEY (NOME)
    REFERENCES ITEM (NOME) ON DELETE CASCADE
);

CREATE TABLE BUFFS(
  NOME VARCHAR2(50),
  DESCRICAO VARCHAR2(255),
  CONSTRAINT PK_BUFFS PRIMARY KEY (NOME,DESCRICAO),
  CONSTRAINT FK_BUFFS_ITEM_NOME FOREIGN KEY (NOME)
    REFERENCES ITEM (NOME) ON DELETE CASCADE
);

CREATE TABLE PARTIDA(
  CODIGO VARCHAR2(10) PRIMARY KEY,
  INICIO_PARTIDA TIMESTAMP NOT NULL,
  MAPA VARCHAR2(20) NOT NULL,
  DURACAO NUMBER(10),
  TIME_V CHAR(1)
);

CREATE TABLE PARTICIPA(
  ID NUMBER(4),
  NICKNAME VARCHAR(50),
  CODIGO VARCHAR2(10),
  TIME CHAR(1),
  KILL NUMBER(4) DEFAULT 0 CONSTRAINT NN_ NOT NULL,
  DEATH NUMBER(4) DEFAULT 0 CONSTRAINT NN_DEATH NOT NULL,
  ASSIST NUMBER(4) DEFAULT 0 CONSTRAINT NN_ASSIST NOT NULL,
  EQUIPAMENTO VARCHAR(20),
  CAMPEAO VARCHAR(50) NOT NULL,
  CONSTRAINT PK_PARTICIPA PRIMARY KEY (ID,NICKNAME,CODIGO),
  CONSTRAINT FK_PARTICIPA_JOGADOR_ID_NICK FOREIGN KEY (ID,NICKNAME)
    REFERENCES JOGADOR (ID,NICKNAME) ON DELETE CASCADE,
  CONSTRAINT FK_PARTICIPA_PARTIDA_CODIGO FOREIGN KEY (CODIGO)
    REFERENCES PARTIDA (CODIGO) ON DELETE CASCADE,
  CONSTRAINT FK_PARTICIPA_ITEM_NOME FOREIGN KEY (EQUIPAMENTO)
    REFERENCES ITEM (NOME) ON DELETE SET NULL,
  CONSTRAINT FK_PARTICIPA_PERSONAGEM_NOME FOREIGN KEY (CAMPEAO)
    REFERENCES PERSONAGEM (NOME)
);