INSERT INTO POSSUI VALUES(2,'Kneallemont','Birgus'); 

INSERT INTO POSSUI VALUES(3,'NIcolashOfSpark','Ursus');
INSERT INTO POSSUI VALUES(3,'NIcolashOfSpark','Lupus');
INSERT INTO POSSUI VALUES(3,'NIcolashOfSpark','Birgus');

INSERT INTO POSSUI VALUES(4,'Thedgme','Manid');
INSERT INTO POSSUI VALUES(4,'Thedgme','Scincus');
INSERT INTO POSSUI VALUES(4,'Thedgme','Strigs');
INSERT INTO POSSUI VALUES(4,'Thedgme','Hercules');
INSERT INTO POSSUI VALUES(4,'Thedgme','Aries');
INSERT INTO POSSUI VALUES(4,'Thedgme','Hyaen');

INSERT INTO POSSUI VALUES(5,'Deplivars','Novem');
INSERT INTO POSSUI VALUES(5,'Deplivars','Crotal');
INSERT INTO POSSUI VALUES(5,'Deplivars','Talpi');
INSERT INTO POSSUI VALUES(5,'Deplivars','Anura');
INSERT INTO POSSUI VALUES(5,'Deplivars','Rhino');
INSERT INTO POSSUI VALUES(5,'Deplivars','Aniso');
INSERT INTO POSSUI VALUES(5,'Deplivars','Manid');
INSERT INTO POSSUI VALUES(5,'Deplivars','Lupus');
INSERT INTO POSSUI VALUES(5,'Deplivars','Aries');
INSERT INTO POSSUI VALUES(5,'Deplivars','Suidae');

INSERT INTO POSSUI VALUES(6,'Overtutremew','Aries');
INSERT INTO POSSUI VALUES(6,'Overtutremew','Alpheus');
INSERT INTO POSSUI VALUES(6,'Overtutremew','Crotal');
INSERT INTO POSSUI VALUES(6,'Overtutremew','Suidae');   

INSERT INTO POSSUI VALUES(7,'Deasind1987','Alpheus');
INSERT INTO POSSUI VALUES(7,'Deasind1987','Novem');
INSERT INTO POSSUI VALUES(7,'Deasind1987','Aniso');
INSERT INTO POSSUI VALUES(7,'Deasind1987','Talpi');
INSERT INTO POSSUI VALUES(7,'Deasind1987','Hyaen');
INSERT INTO POSSUI VALUES(7,'Deasind1987','Bison');

INSERT INTO POSSUI VALUES(8,'Allontention','Ursus');
INSERT INTO POSSUI VALUES(8,'Allontention','Aries');
INSERT INTO POSSUI VALUES(8,'Allontention','Rhino');
INSERT INTO POSSUI VALUES(8,'Allontention','Hyaen');
INSERT INTO POSSUI VALUES(8,'Allontention','Bison');
INSERT INTO POSSUI VALUES(8,'Allontention','Talpi');
INSERT INTO POSSUI VALUES(8,'Allontention','Novem');

INSERT INTO POSSUI VALUES(9,'Difter','Anura');
INSERT INTO POSSUI VALUES(9,'Difter','Vultur');
INSERT INTO POSSUI VALUES(9,'Difter','Manid');
INSERT INTO POSSUI VALUES(9,'Difter','Lupus');
INSERT INTO POSSUI VALUES(9,'Difter','Aries');
INSERT INTO POSSUI VALUES(9,'Difter','Aniso');
INSERT INTO POSSUI VALUES(9,'Difter','Talpi');

INSERT INTO POSSUI VALUES(10,'Yemand','Anura');
INSERT INTO POSSUI VALUES(10,'Yemand','Bato');
INSERT INTO POSSUI VALUES(10,'Yemand','Birgus');
INSERT INTO POSSUI VALUES(10,'Yemand','Alpheus');
INSERT INTO POSSUI VALUES(10,'Yemand','Crotal');
INSERT INTO POSSUI VALUES(10,'Yemand','Vultur');
INSERT INTO POSSUI VALUES(10,'Yemand','Lupus');
INSERT INTO POSSUI VALUES(10,'Yemand','Hyaen');

INSERT INTO POSSUI VALUES(11,'Whavence','Alpheus');
INSERT INTO POSSUI VALUES(11,'Whavence','Suidae');

INSERT INTO POSSUI VALUES(12,'Glan2006','Anura');

INSERT INTO POSSUI VALUES(13,'Coleaked','Hercules');
INSERT INTO POSSUI VALUES(13,'Coleaked','Rhino');
INSERT INTO POSSUI VALUES(13,'Coleaked','Scincus');
INSERT INTO POSSUI VALUES(13,'Coleaked','Strigs');
INSERT INTO POSSUI VALUES(13,'Coleaked','Manid');
INSERT INTO POSSUI VALUES(13,'Coleaked','Hyaen');
INSERT INTO POSSUI VALUES(13,'Coleaked','Alpheus');

INSERT INTO POSSUI VALUES(14,'Alled2000','Anura');
INSERT INTO POSSUI VALUES(14,'Alled2000','Bison');
INSERT INTO POSSUI VALUES(14,'Alled2000','Novem');
INSERT INTO POSSUI VALUES(14,'Alled2000','Rhino');
INSERT INTO POSSUI VALUES(14,'Alled2000','Suidae');
INSERT INTO POSSUI VALUES(14,'Alled2000','Talpi');
INSERT INTO POSSUI VALUES(14,'Alled2000','Aniso');
INSERT INTO POSSUI VALUES(14,'Alled2000','Birgus');
INSERT INTO POSSUI VALUES(14,'Alled2000','Hercules');
INSERT INTO POSSUI VALUES(14,'Alled2000','Ursus');

INSERT INTO POSSUI VALUES(15,'Eventer','Crotal');
INSERT INTO POSSUI VALUES(15,'Eventer','Ursus');
INSERT INTO POSSUI VALUES(15,'Eventer','Strigs');
INSERT INTO POSSUI VALUES(15,'Eventer','Alpheus');
INSERT INTO POSSUI VALUES(15,'Eventer','Lupus');
INSERT INTO POSSUI VALUES(15,'Eventer','Hercules');
INSERT INTO POSSUI VALUES(15,'Eventer','Birgus');
INSERT INTO POSSUI VALUES(15,'Eventer','Vultur');

INSERT INTO POSSUI VALUES(16,'Excul2002','Bato');
INSERT INTO POSSUI VALUES(16,'Excul2002','Rhino');
INSERT INTO POSSUI VALUES(16,'Excul2002','Bison');
INSERT INTO POSSUI VALUES(16,'Excul2002','Suidae');
INSERT INTO POSSUI VALUES(16,'Excul2002','Birgus');
INSERT INTO POSSUI VALUES(16,'Excul2002','Manid');

INSERT INTO POSSUI VALUES(17,'Exach1985','Rose');
INSERT INTO POSSUI VALUES(17,'Exach1985','Aniso');
INSERT INTO POSSUI VALUES(17,'Exach1985','Vultur');
INSERT INTO POSSUI VALUES(17,'Exach1985','Anura');
INSERT INTO POSSUI VALUES(17,'Exach1985','Manid');
INSERT INTO POSSUI VALUES(17,'Exach1985','Lupus');

INSERT INTO POSSUI VALUES(18,'Slengslas1992','Aries');

INSERT INTO POSSUI VALUES(19,'Dithey','Alpheus');
INSERT INTO POSSUI VALUES(19,'Dithey','Aries');
INSERT INTO POSSUI VALUES(19,'Dithey','Bison');
INSERT INTO POSSUI VALUES(19,'Dithey','Birgus');
INSERT INTO POSSUI VALUES(19,'Dithey','Crotal');
INSERT INTO POSSUI VALUES(19,'Dithey','Bato');
INSERT INTO POSSUI VALUES(19,'Dithey','Manid');
INSERT INTO POSSUI VALUES(19,'Dithey','Novem');
INSERT INTO POSSUI VALUES(19,'Dithey','Vultur');

INSERT INTO POSSUI VALUES(20,'Upostionots','Talpi');
INSERT INTO POSSUI VALUES(20,'Upostionots','Alpheus');

INSERT INTO POSSUI VALUES(21,'Theighavell08','Talpi');
INSERT INTO POSSUI VALUES(21,'Theighavell08','Birgus');
INSERT INTO POSSUI VALUES(21,'Theighavell08','Suidae');

INSERT INTO POSSUI VALUES(22,'Sithen','Rhino');
INSERT INTO POSSUI VALUES(22,'Sithen','Novem');
INSERT INTO POSSUI VALUES(22,'Sithen','Talpi');
INSERT INTO POSSUI VALUES(22,'Sithen','Strigs');

INSERT INTO POSSUI VALUES(23,'Gribladeen1992','Crotal');
INSERT INTO POSSUI VALUES(23,'Gribladeen1992','Rhino');

INSERT INTO POSSUI VALUES(25,'Brainitterem','Bato');
INSERT INTO POSSUI VALUES(25,'Brainitterem','Vultur');
INSERT INTO POSSUI VALUES(25,'Brainitterem','Novem');
INSERT INTO POSSUI VALUES(25,'Brainitterem','Crotal');
INSERT INTO POSSUI VALUES(25,'Brainitterem','Suidae');

INSERT INTO POSSUI VALUES(26,'Sithereony','Rose');
INSERT INTO POSSUI VALUES(26,'Sithereony','Scincus');
INSERT INTO POSSUI VALUES(26,'Sithereony','Anura');
INSERT INTO POSSUI VALUES(26,'Sithereony','Bato');
INSERT INTO POSSUI VALUES(26,'Sithereony','Bison');
INSERT INTO POSSUI VALUES(26,'Sithereony','Alpheus');
INSERT INTO POSSUI VALUES(26,'Sithereony','Strigs');
INSERT INTO POSSUI VALUES(26,'Sithereony','Novem');

INSERT INTO POSSUI VALUES(27,'Inihis','Anura');
INSERT INTO POSSUI VALUES(27,'Inihis','Vultur');
INSERT INTO POSSUI VALUES(27,'Inihis','Lupus');
INSERT INTO POSSUI VALUES(27,'Inihis','Strigs');
INSERT INTO POSSUI VALUES(27,'Inihis','Suidae');

INSERT INTO POSSUI VALUES(28,'Canualal','Aniso');

INSERT INTO POSSUI VALUES(29,'Fating','Lupus');

INSERT INTO POSSUI VALUES(30,'Peopeor','Bato');
INSERT INTO POSSUI VALUES(30,'Peopeor','Ursus');
INSERT INTO POSSUI VALUES(30,'Peopeor','Alpheus');
INSERT INTO POSSUI VALUES(30,'Peopeor','Crotal');
INSERT INTO POSSUI VALUES(30,'Peopeor','Suidae');
INSERT INTO POSSUI VALUES(30,'Peopeor','Bison');

INSERT INTO POSSUI VALUES(31,'Squing','Strigs');
INSERT INTO POSSUI VALUES(31,'Squing','Crotal');
INSERT INTO POSSUI VALUES(31,'Squing','Bison');
INSERT INTO POSSUI VALUES(31,'Squing','Scincus');
INSERT INTO POSSUI VALUES(31,'Squing','Vultur');
INSERT INTO POSSUI VALUES(31,'Squing','Suidae');
INSERT INTO POSSUI VALUES(31,'Squing','Talpi');
INSERT INTO POSSUI VALUES(31,'Squing','Hercules');

INSERT INTO POSSUI VALUES(32,'Tatromer','Suidae');
INSERT INTO POSSUI VALUES(32,'Tatromer','Birgus');
INSERT INTO POSSUI VALUES(32,'Tatromer','Bato');
INSERT INTO POSSUI VALUES(32,'Tatromer','Rhino');
INSERT INTO POSSUI VALUES(32,'Tatromer','Hyaen');
INSERT INTO POSSUI VALUES(32,'Tatromer','Ursus');
INSERT INTO POSSUI VALUES(32,'Tatromer','Anura');
INSERT INTO POSSUI VALUES(32,'Tatromer','Alpheus');
INSERT INTO POSSUI VALUES(32,'Tatromer','Novem');
INSERT INTO POSSUI VALUES(32,'Tatromer','Manid');

INSERT INTO POSSUI VALUES(33,'Eyettaking','Anura');
INSERT INTO POSSUI VALUES(33,'Eyettaking','Talpi');
INSERT INTO POSSUI VALUES(33,'Eyettaking','Vultur');
INSERT INTO POSSUI VALUES(33,'Eyettaking','Suidae');
INSERT INTO POSSUI VALUES(33,'Eyettaking','Birgus');
INSERT INTO POSSUI VALUES(33,'Eyettaking','Bato');
INSERT INTO POSSUI VALUES(33,'Eyettaking','Hyaen');
INSERT INTO POSSUI VALUES(33,'Eyettaking','Lupus');

INSERT INTO POSSUI VALUES(34,'Eyettaking','Novem');
INSERT INTO POSSUI VALUES(34,'Eyettaking','Crotal');
INSERT INTO POSSUI VALUES(34,'Eyettaking','Alpheus');

INSERT INTO POSSUI VALUES(35,'Harriew','Hercules');
INSERT INTO POSSUI VALUES(35,'Harriew','Ursus');
INSERT INTO POSSUI VALUES(35,'Harriew','Rose');
INSERT INTO POSSUI VALUES(35,'Harriew','Hyaen');
INSERT INTO POSSUI VALUES(35,'Harriew','Strigs');

INSERT INTO POSSUI VALUES(36,'MeloPinto','Rhino');
INSERT INTO POSSUI VALUES(36,'MeloPinto','Alpheus');
INSERT INTO POSSUI VALUES(36,'MeloPinto','Hercules');
INSERT INTO POSSUI VALUES(36,'MeloPinto','Scincus');
INSERT INTO POSSUI VALUES(36,'MeloPinto','Crotal');
INSERT INTO POSSUI VALUES(36,'MeloPinto','Lupus');
INSERT INTO POSSUI VALUES(36,'MeloPinto','Talpi');
INSERT INTO POSSUI VALUES(36,'MeloPinto','Manid');

INSERT INTO POSSUI VALUES(37,'Forded','Vultur');

INSERT INTO POSSUI VALUES(38,'Brind1989','Lupus');
INSERT INTO POSSUI VALUES(38,'Brind1989','Talpi');
INSERT INTO POSSUI VALUES(38,'Brind1989','Birgus');
INSERT INTO POSSUI VALUES(38,'Brind1989','Rose');
INSERT INTO POSSUI VALUES(38,'Brind1989','Vultur');
INSERT INTO POSSUI VALUES(38,'Brind1989','Ursus');
INSERT INTO POSSUI VALUES(38,'Brind1989','Hercules');
INSERT INTO POSSUI VALUES(38,'Brind1989','Aries');
INSERT INTO POSSUI VALUES(38,'Brind1989','Scincus');

INSERT INTO POSSUI VALUES(39,'Anyinct','Hercules');
INSERT INTO POSSUI VALUES(39,'Anyinct','Bison');
INSERT INTO POSSUI VALUES(39,'Anyinct','Ursus');
INSERT INTO POSSUI VALUES(39,'Anyinct','Bato');
INSERT INTO POSSUI VALUES(39,'Anyinct','Vultur');